plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

def props = new Properties()
file("../signing/cmi-credentials.properties").withInputStream { props.load(it) }

android {

    namespace 'com.rguzmanc.cmi'
    compileSdk 35

    defaultConfig {
        applicationId "com.rguzmanc.cmi"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 13
        versionName "1.0.2"

        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("../signing/cmi-android-keystore-signing.keystore")
            storePassword props.getProperty("store-password")
            keyAlias props.getProperty("alias")
            keyPassword props.getProperty("alias-password")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.jakewharton.timber
    implementation(platform(libs.koin.bom))
    implementation(libs.koin.android)

    implementation project(":presentation")

    testImplementation libs.androidx.test.junit
    testImplementation libs.androidx.test.junit.ktx
    testImplementation libs.androidx.test.core
    testImplementation libs.androidx.test.core.ktx
    testImplementation libs.robolectric
}