name: CMI - PECS Android Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Set Up JDK Environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run lint rules
        run: ./gradlew lintDebug --stacktrace
      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest --stacktrace
      - name: Build App
        run: ./gradlew build
